// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh8msqkJUwy58bowHVe0skbrKghZm0jK0',
    appId: '1:76212519648:web:56fa99923e518ea2820685',
    messagingSenderId: '76212519648',
    projectId: 'grocery-store-e0880',
    authDomain: 'grocery-store-e0880.firebaseapp.com',
    storageBucket: 'grocery-store-e0880.appspot.com',
    measurementId: 'G-FNNWGMP8Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU_zQXVxrVurGOKi5ljsm6n5ezxgpckGY',
    appId: '1:76212519648:android:7fa1de9e0dd49609820685',
    messagingSenderId: '76212519648',
    projectId: 'grocery-store-e0880',
    storageBucket: 'grocery-store-e0880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV76lHYeymU6PHDStRtg8etqoTIp6REfk',
    appId: '1:76212519648:ios:582e84e3a5cc859a820685',
    messagingSenderId: '76212519648',
    projectId: 'grocery-store-e0880',
    storageBucket: 'grocery-store-e0880.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV76lHYeymU6PHDStRtg8etqoTIp6REfk',
    appId: '1:76212519648:ios:582e84e3a5cc859a820685',
    messagingSenderId: '76212519648',
    projectId: 'grocery-store-e0880',
    storageBucket: 'grocery-store-e0880.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh8msqkJUwy58bowHVe0skbrKghZm0jK0',
    appId: '1:76212519648:web:a4f1dc19c7f93876820685',
    messagingSenderId: '76212519648',
    projectId: 'grocery-store-e0880',
    authDomain: 'grocery-store-e0880.firebaseapp.com',
    storageBucket: 'grocery-store-e0880.appspot.com',
    measurementId: 'G-X6GTJG441K',
  );
}
